declare const _default: {
    dbConnect: (config: Record<string, unknown>) => Promise<any>;
    dbDisconnect: (id: string) => Promise<any>;
    dbQuery: (id: string, sql: string) => Promise<any>;
    dbGetTables: (id: string, dbName?: string) => Promise<any>;
    dbGetDatabases: (id: string) => Promise<any>;
    dbGetViews: (id: string, dbName: string) => Promise<any>;
    dbGetTableData: (id: string, table: string, limit: number, offset: number, dbName?: string, orderBy?: string, orderDir?: string) => Promise<any>;
    dbTest: (config: Record<string, unknown>) => Promise<any>;
    dbRedisKeys: (id: string, pattern: string) => Promise<any>;
    dbRedisGet: (id: string, key: string) => Promise<any>;
    dbRedisKeyInfo: (id: string, key: string) => Promise<any>;
    dbRedisKeyValue: (id: string, key: string) => Promise<any>;
    dbRedisSetKey: (id: string, key: string, type: string, value: any) => Promise<any>;
    dbRedisAddKey: (id: string, key: string, type: string, value?: any) => Promise<any>;
    dbRedisDeleteKey: (id: string, key: string) => Promise<any>;
    dbRedisExec: (id: string, command: string) => Promise<any>;
    dbRedisDatabases: (id: string) => Promise<any>;
    dbRedisKeysByType: (id: string, dbIndex: number, pattern: string) => Promise<any>;
    dbRedisKeysTree: (id: string, dbIndex: number, prefix: string, limit?: number) => Promise<any>;
    dbRedisStreams: (id: string, dbIndex: number, pattern?: string, loadMore?: boolean) => Promise<any>;
    dbRedisStreamInfo: (id: string, dbIndex: number, key: string) => Promise<any>;
    dbRedisStreamConsumers: (id: string, dbIndex: number, key: string, group: string) => Promise<any>;
    dbRedisStreamMessages: (id: string, dbIndex: number, key: string, start?: string, end?: string, count?: number) => Promise<any>;
    dbRedisStreamAdd: (id: string, dbIndex: number, key: string, fields: Record<string, string>, maxlen?: number) => Promise<any>;
    dbRedisStreamDel: (id: string, dbIndex: number, key: string, messageId: string) => Promise<any>;
    dbRedisStreamGroupCreate: (id: string, dbIndex: number, key: string, group: string, startId?: string) => Promise<any>;
    dbRedisStreamGroupDestroy: (id: string, dbIndex: number, key: string, group: string) => Promise<any>;
    dbRedisStreamPending: (id: string, dbIndex: number, key: string, group: string, startId?: string, endId?: string, count?: number) => Promise<any>;
    dbRedisStreamClaim: (id: string, dbIndex: number, key: string, group: string, consumer: string, messageId: string, minIdleTime?: number) => Promise<any>;
    dbRedisStreamAck: (id: string, dbIndex: number, key: string, group: string, messageId: string) => Promise<any>;
    dbRedisStreamDelete: (id: string, dbIndex: number, key: string) => Promise<any>;
    dbRedisScanKeys: (id: string, dbIndex: number, pattern: string, type?: string) => Promise<any>;
    dbRedisZSetRange: (id: string, dbIndex: number, key: string, minScore: number, maxScore: number, count: number) => Promise<any>;
    dbRedisZSetRemove: (id: string, dbIndex: number, key: string, value: string) => Promise<any>;
    dbRedisZSetAdd: (id: string, dbIndex: number, key: string, value: string, score: number) => Promise<any>;
    dbRedisStreamTrim: (id: string, dbIndex: number, key: string, maxLen: number) => Promise<any>;
    dbRedisStreamRetry: (id: string, dbIndex: number, key: string, group: string, messageId: string) => Promise<any>;
    dbGetCreateSql: (id: string, table: string, dbName?: string) => Promise<any>;
    dbGetTablePrimaryKeys: (id: string, table: string, dbName?: string) => Promise<any>;
    dbUpdateTableRow: (id: string, table: string, oldRow: Record<string, any>, newRow: Record<string, any>, dbName?: string) => Promise<any>;
    dbInsertTableRow: (id: string, table: string, row: Record<string, any>, dbName?: string) => Promise<any>;
    dbDeleteTableRow: (id: string, table: string, row: Record<string, any>, dbName?: string) => Promise<any>;
    dbGetTableStructure: (id: string, tableName: string, dbName?: string) => Promise<any>;
    dbCompareStructures: (sourceId: string, targetId: string, tableName: string, sourceDbName?: string, targetDbName?: string) => Promise<any>;
    dbExecuteStructureSync: (targetId: string, sqls: string[], targetDbName?: string) => Promise<any>;
    dbCompareData: (sourceId: string, targetId: string, tableName: string, primaryKeys: string[], columns: string[], sourceDbName?: string, targetDbName?: string, tablePrimaryKeys?: string[]) => Promise<any>;
    dbExecuteDataSync: (options: Record<string, any>) => Promise<any>;
    dbGetTableDataFiltered: (options: Record<string, any>) => Promise<any>;
    dbBackupCreate: (connectionId: string, dbName: string, objects: Array<{
        type: string;
        name: string;
        includeData: boolean;
    }>, outputPath?: string) => Promise<any>;
    dbBackupRestore: (connectionId: string, nb3FilePath: string) => Promise<any>;
    dbBackupList: (connectionId?: string) => Promise<any>;
    dbBackupDelete: (filePath: string) => Promise<any>;
    dbBackupOnProgress: (callback: (_event: any, data: {
        stage: string;
        progress: number;
    }) => void) => Electron.IpcRenderer;
    dbBackupOffProgress: (callback: (_event: any, data: {
        stage: string;
        progress: number;
    }) => void) => Electron.IpcRenderer;
    dbAddColumn: (id: string, dbName: string | undefined, tableName: string, column: Record<string, any>) => Promise<any>;
    dbModifyColumn: (id: string, dbName: string | undefined, tableName: string, oldColumn: string, newColumn: Record<string, any>) => Promise<any>;
    dbDropColumn: (id: string, dbName: string | undefined, tableName: string, columnName: string) => Promise<any>;
    dbRenameColumn: (id: string, dbName: string | undefined, tableName: string, oldName: string, newName: string) => Promise<any>;
    dbAddIndex: (id: string, dbName: string | undefined, tableName: string, indexDef: Record<string, any>) => Promise<any>;
    dbDropIndex: (id: string, dbName: string | undefined, tableName: string, indexName: string) => Promise<any>;
    dbRenameTable: (id: string, dbName: string | undefined, oldName: string, newName: string) => Promise<any>;
    dbAlterTable: (id: string, dbName: string | undefined, tableName: string, operations: Record<string, any>[]) => Promise<any>;
};
export default _default;
