import type { WeeklyReport, AutoBackupSettings } from './preload-core';
declare const _default: {
    exportData: (options: Record<string, unknown>) => Promise<any>;
    importJson: (options: Record<string, unknown>) => Promise<any>;
    exportCsv: (options: Record<string, unknown>) => Promise<any>;
    exportWordReport: (reportData: Record<string, unknown>) => Promise<any>;
    saveWeeklyReport: (report: WeeklyReport) => Promise<any>;
    getWeeklyReports: (limit: number) => Promise<any>;
    getWeeklyReport: (id: number) => Promise<any>;
    setAutoBackup: (settings: AutoBackupSettings) => Promise<any>;
    onAutoBackupCompleted: (callback: (data: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    getAppVersion: () => Promise<any>;
    checkForUpdates: () => Promise<any>;
    installUpdate: () => Promise<any>;
    onUpdateChecking: (callback: () => void) => () => Electron.IpcRenderer;
    onUpdateAvailable: (callback: (info: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onUpdateNotAvailable: (callback: (info: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onUpdateDownloadProgress: (callback: (progress: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onUpdateDownloaded: (callback: (info: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onUpdateError: (callback: (error: string) => void) => () => Electron.IpcRenderer;
    onMenuNewTask: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuExportMarkdown: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuExportWord: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuExportJson: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuImportJson: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuClearCompleted: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuSearchTasks: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuSelectAll: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuDeleteSelected: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuToggleTheme: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuToggleLocale: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuSwitchView: (callback: (view: string) => void) => () => Electron.IpcRenderer;
    onMenuToggleLanPanel: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuToggleComplete: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuSetPriority: (callback: (priority: string) => void) => () => Electron.IpcRenderer;
    onMenuSetTag: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuAbout: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuShortcutsHelp: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuCheckUpdate: (callback: () => void) => () => Electron.IpcRenderer;
    onMenuNav: (callback: (view: string) => void) => () => Electron.IpcRenderer;
    onQuickSwitch: (callback: () => void) => () => Electron.IpcRenderer;
    triggerMenuNav: (view: string) => void;
    onDataChanged: (callback: (data: {
        type: string;
        data?: unknown;
    }) => void) => () => Electron.IpcRenderer;
};
export default _default;
