import type { Peer, FileTransfer, LanMessage, Todo } from './preload-core';
declare const _default: {
    getPeers: () => Promise<any>;
    sendMessage: (peerId: string, message: string) => Promise<any>;
    showOpenDialog: (options?: {
        title?: string;
        properties?: string[];
    }) => Promise<any>;
    broadcastMessage: (message: string) => Promise<any>;
    assignTask: (peerId: string, task: unknown) => Promise<any>;
    syncTaskStatus: (todo: unknown) => Promise<any>;
    getUserInfo: () => Promise<any>;
    setNickName: (name: string) => Promise<any>;
    setAvatar: (emoji: string) => Promise<any>;
    setStatus: (status: string) => Promise<any>;
    getStatus: () => Promise<any>;
    getNetworkInfo: () => Promise<any>;
    checkNetworkPermission: () => Promise<any>;
    getPermissionStatus: () => Promise<any>;
    refreshDiscovery: () => Promise<any>;
    getReceivePath: () => Promise<any>;
    setReceivePath: (path: string) => Promise<any>;
    openFileFolder: (filePath: string) => Promise<any>;
    openFile: (filePath: string) => Promise<any>;
    broadcastTaskUpdate: (todo: Todo) => Promise<any>;
    broadcastTaskStatusChange: (todo: Todo) => Promise<any>;
    broadcastTaskComment: (todoId: string, comment: string) => Promise<any>;
    broadcastCollaborationStarted: (todoId: string, editorName: string) => Promise<any>;
    broadcastCollaborationEnded: (todoId: string, editorName: string) => Promise<any>;
    sendFile: (peerId: string, filePath: string, fileName: string, resumeOffset: number, fileId?: string) => Promise<any>;
    getMessageHistory: (limit: number, offset: number) => Promise<any>;
    getMessagesBetween: (userId1: string, userId2: string, limit: number, offset: number) => Promise<any>;
    markMessagesRead: (myUserId: string, peerId: string) => Promise<any>;
    getUnreadCount: (myUserId: string, peerId: string) => Promise<any>;
    getAllUnreadCounts: (myUserId: string) => Promise<any>;
    getFileTransferHistory: (limit: number, offset: number) => Promise<any>;
    onLanPeerDiscovered: (callback: (peer: Peer) => void) => () => Electron.IpcRenderer;
    onLanPeerLost: (callback: (peer: Peer) => void) => () => Electron.IpcRenderer;
    onMessage: (callback: (data: LanMessage) => void) => () => Electron.IpcRenderer;
    onTaskAssigned: (callback: (data: LanMessage) => void) => () => Electron.IpcRenderer;
    onTaskUpdated: (callback: (data: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onTaskStatusChanged: (callback: (data: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onTaskCommentAdded: (callback: (data: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onCollaborationStarted: (callback: (data: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onCollaborationEnded: (callback: (data: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onFileTransferStarted: (callback: (data: FileTransfer) => void) => () => Electron.IpcRenderer;
    onFileTransferProgress: (callback: (data: FileTransfer) => void) => () => Electron.IpcRenderer;
    onFileTransferCompleted: (callback: (data: FileTransfer) => void) => () => Electron.IpcRenderer;
    onFileTransferError: (callback: (data: FileTransfer) => void) => () => Electron.IpcRenderer;
    onFileReceived: (callback: (data: FileTransfer) => void) => () => Electron.IpcRenderer;
    screenshot: () => Promise<any>;
    saveTempFile: (base64Data: string, fileName: string) => Promise<any>;
    loadLocalFileAsBase64: (filePath: string) => Promise<any>;
};
export default _default;
