import type { CicdConfig, DeployModule } from './preload-core';
declare const _default: {
    getCicdConfigs: () => Promise<any>;
    getCicdGroups: () => Promise<any>;
    getCicdConfig: (projectId: string) => Promise<any>;
    getCicdConfigById: (configId: string) => Promise<any>;
    addCicdConfig: (config: CicdConfig) => Promise<any>;
    updateCicdConfig: (config: CicdConfig) => Promise<any>;
    deleteCicdConfig: (configId: string) => Promise<any>;
    getDeployModules: (configId: string) => Promise<any>;
    addDeployModule: (module: DeployModule) => Promise<any>;
    updateDeployModule: (module: DeployModule) => Promise<any>;
    deleteDeployModule: (moduleId: string) => Promise<any>;
    getDeployLogs: (projectId: string, limit: number) => Promise<any>;
    getDeployStepLogs: (deployLogId: string) => Promise<any>;
    deploy: (configId: string, confirmed?: boolean) => Promise<any>;
    cancelDeploy: (configId: string) => Promise<any>;
    rollback: (configId: string, deployHistoryId: string) => Promise<any>;
    rollbackDeploy: (deployLogId: string) => Promise<any>;
    readLogFile: (filePath: string) => Promise<any>;
    testSsh: (config: Record<string, unknown>) => Promise<any>;
    detectBuildTools: () => Promise<any>;
    detectToolPaths: () => Promise<any>;
    detectSdkVersions: () => Promise<any>;
    getDeployHistory: (projectId: string, limit: number) => Promise<any>;
    checkMavenAvailable: () => Promise<any>;
    checkJavaAvailable: (javaHome?: string) => Promise<any>;
    checkNodeAvailable: (nodeHome?: string) => Promise<any>;
    scanProjectModules: (projectPath: string) => Promise<any>;
    onDeployProgress: (callback: (data: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onDeployNotification: (callback: (data: Record<string, unknown>) => void) => () => Electron.IpcRenderer;
    onDeployLogIdCreated: (callback: (data: {
        deployLogId: string;
    }) => void) => () => Electron.IpcRenderer;
};
export default _default;
