"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/** All Git operations API */
const electron_1 = require("electron");
exports.default = {
    // Git Commits & Branches
    getGitCommits: (gitUrl, sinceDate, branch) => electron_1.ipcRenderer.invoke('git:get-commits', gitUrl, branch, sinceDate),
    getGitBranches: (gitUrl) => electron_1.ipcRenderer.invoke('git:get-branches', gitUrl),
    scanLocalGitRepos: () => electron_1.ipcRenderer.invoke('git:scan-local-repos'),
    validateGitRepoPath: (path) => electron_1.ipcRenderer.invoke('git:validate-repo-path', path),
    // Git Operations
    gitStatus: (repoPath) => electron_1.ipcRenderer.invoke('git:status', repoPath),
    gitLog: (repoPath, options) => electron_1.ipcRenderer.invoke('git:log', repoPath, options),
    gitBranches: (repoPath) => electron_1.ipcRenderer.invoke('git:branches', repoPath),
    gitCurrentBranch: (repoPath) => electron_1.ipcRenderer.invoke('git:current-branch', repoPath),
    gitDiff: (repoPath, file) => electron_1.ipcRenderer.invoke('git:diff', repoPath, file),
    gitCommitDiff: (repoPath, commitHash) => electron_1.ipcRenderer.invoke('git:commit-diff', repoPath, commitHash),
    gitCommit: (repoPath, message, files) => electron_1.ipcRenderer.invoke('git:commit', repoPath, message, files),
    gitAdd: (repoPath, files) => electron_1.ipcRenderer.invoke('git:add', repoPath, files),
    gitReset: (repoPath, file) => electron_1.ipcRenderer.invoke('git:reset', repoPath, file),
    gitCheckout: (repoPath, branch) => electron_1.ipcRenderer.invoke('git:checkout', repoPath, branch),
    gitCreateBranch: (repoPath, branchName, from) => electron_1.ipcRenderer.invoke('git:create-branch', repoPath, branchName, from),
    gitDeleteBranch: (repoPath, branchName, force) => electron_1.ipcRenderer.invoke('git:delete-branch', repoPath, branchName, force),
    gitMerge: (repoPath, branch) => electron_1.ipcRenderer.invoke('git:merge', repoPath, branch),
    gitPull: (repoPath) => electron_1.ipcRenderer.invoke('git:pull', repoPath),
    gitPush: (repoPath) => electron_1.ipcRenderer.invoke('git:push', repoPath),
    gitDiscardChanges: (repoPath, file) => electron_1.ipcRenderer.invoke('git:discard-changes', repoPath, file),
    // Git Stash
    gitStashSave: (repoPath, options) => electron_1.ipcRenderer.invoke('git:stash-save', repoPath, options),
    gitStashList: (repoPath) => electron_1.ipcRenderer.invoke('git:stash-list', repoPath),
    gitStashApply: (repoPath, stashRef) => electron_1.ipcRenderer.invoke('git:stash-apply', repoPath, stashRef),
    gitStashDrop: (repoPath, stashRef) => electron_1.ipcRenderer.invoke('git:stash-drop', repoPath, stashRef),
    gitStashPop: (repoPath, stashRef) => electron_1.ipcRenderer.invoke('git:stash-pop', repoPath, stashRef),
    gitStashShow: (repoPath, stashRef) => electron_1.ipcRenderer.invoke('git:stash-show', repoPath, stashRef),
    // Git Cherry-pick & Revert
    gitCherryPick: (repoPath, commitHash, options) => electron_1.ipcRenderer.invoke('git:cherry-pick', repoPath, commitHash, options),
    gitRevert: (repoPath, commitHash, options) => electron_1.ipcRenderer.invoke('git:revert', repoPath, commitHash, options),
    // Git Tags
    gitListTags: (repoPath) => electron_1.ipcRenderer.invoke('git:tag-list', repoPath),
    gitCreateTag: (repoPath, tagName, options) => electron_1.ipcRenderer.invoke('git:tag-create', repoPath, tagName, options),
    gitDeleteTag: (repoPath, tagName) => electron_1.ipcRenderer.invoke('git:tag-delete', repoPath, tagName),
    // Git File History & Compare
    gitFileHistory: (repoPath, filePath, options) => electron_1.ipcRenderer.invoke('git:file-history', repoPath, filePath, options),
    gitCompareBranches: (repoPath, targetBranch, sourceBranch) => electron_1.ipcRenderer.invoke('git:compare-branches', repoPath, targetBranch, sourceBranch),
    gitLogGraph: (repoPath, limit) => electron_1.ipcRenderer.invoke('git:log-graph', repoPath, limit),
    gitExec: (repoPath, args) => electron_1.ipcRenderer.invoke('git:exec', repoPath, args),
    // Git Advanced
    gitAmendCommit: (repoPath, message) => electron_1.ipcRenderer.invoke('git:amend-commit', repoPath, message),
    gitResetToCommit: (repoPath, commitHash, mode) => electron_1.ipcRenderer.invoke('git:reset-to-commit', repoPath, commitHash, mode),
    gitRenameBranch: (repoPath, oldName, newName) => electron_1.ipcRenderer.invoke('git:rename-branch', repoPath, oldName, newName),
    gitFetch: (repoPath, remote) => electron_1.ipcRenderer.invoke('git:fetch', repoPath, remote),
    gitForcePush: (repoPath) => electron_1.ipcRenderer.invoke('git:force-push', repoPath),
    gitUnpushedCommits: (repoPath) => electron_1.ipcRenderer.invoke('git:unpushed-commits', repoPath),
    gitIncomingCommits: (repoPath) => electron_1.ipcRenderer.invoke('git:incoming-commits', repoPath),
    gitCheckoutRemoteBranch: (repoPath, remote, branch) => electron_1.ipcRenderer.invoke('git:checkout-remote-branch', repoPath, remote, branch),
    gitConflictFiles: (repoPath) => electron_1.ipcRenderer.invoke('git:conflict-files', repoPath),
    gitAcceptConflict: (repoPath, file, strategy) => electron_1.ipcRenderer.invoke('git:accept-conflict', repoPath, file, strategy),
    gitInteractiveRebaseList: (repoPath, commitHash) => electron_1.ipcRenderer.invoke('git:interactive-rebase-list', repoPath, commitHash),
    gitInteractiveRebase: (repoPath, commitHash, actions) => electron_1.ipcRenderer.invoke('git:interactive-rebase', repoPath, commitHash, actions),
    gitRemotes: (repoPath) => electron_1.ipcRenderer.invoke('git:remotes', repoPath),
    gitAddRemote: (repoPath, name, url) => electron_1.ipcRenderer.invoke('git:add-remote', repoPath, name, url),
    gitRemoveRemote: (repoPath, name) => electron_1.ipcRenderer.invoke('git:remove-remote', repoPath, name),
    gitSetRemoteUrl: (repoPath, name, url) => electron_1.ipcRenderer.invoke('git:set-remote-url', repoPath, name, url),
    gitAddGitignore: (repoPath, pattern) => electron_1.ipcRenderer.invoke('git:add-gitignore', repoPath, pattern),
    gitGetGitignore: (repoPath) => electron_1.ipcRenderer.invoke('git:get-gitignore', repoPath),
    gitSubmodules: (repoPath) => electron_1.ipcRenderer.invoke('git:submodules', repoPath),
    gitUndoLastCommit: (repoPath) => electron_1.ipcRenderer.invoke('git:undo-last-commit', repoPath),
    gitPushTags: (repoPath, remote) => electron_1.ipcRenderer.invoke('git:push-tags', repoPath, remote),
    gitDeleteRemoteBranch: (repoPath, remote, branchName) => electron_1.ipcRenderer.invoke('git:delete-remote-branch', repoPath, remote, branchName),
    gitClean: (repoPath, options) => electron_1.ipcRenderer.invoke('git:clean', repoPath, options),
    gitFileAtRevision: (repoPath, filePath, revision) => electron_1.ipcRenderer.invoke('git:file-at-revision', repoPath, filePath, revision),
    gitDiffFileRevision: (repoPath, filePath, rev1, rev2) => electron_1.ipcRenderer.invoke('git:diff-file-revision', repoPath, filePath, rev1, rev2),
    gitCompareCommits: (repoPath, commit1, commit2, filePath) => electron_1.ipcRenderer.invoke('git:compare-commits', repoPath, commit1, commit2, filePath),
    gitCreatePatch: (repoPath, commitRange, filePaths) => electron_1.ipcRenderer.invoke('git:create-patch', repoPath, commitRange, filePaths),
    gitApplyPatch: (repoPath, patchContent, options) => electron_1.ipcRenderer.invoke('git:apply-patch', repoPath, patchContent, options),
    gitCherryPickMultiple: (repoPath, hashes, options) => electron_1.ipcRenderer.invoke('git:cherry-pick-multiple', repoPath, hashes, options),
    gitBranchFromTag: (repoPath, branchName, tagName) => electron_1.ipcRenderer.invoke('git:branch-from-tag', repoPath, branchName, tagName),
    gitSubmoduleList: (repoPath) => electron_1.ipcRenderer.invoke('git:submodule-list', repoPath),
    gitSubmoduleInit: (repoPath, recursive) => electron_1.ipcRenderer.invoke('git:submodule-init', repoPath, recursive),
    gitCommitCount: (repoPath, branch) => electron_1.ipcRenderer.invoke('git:commit-count', repoPath, branch),
    gitChangedFiles: (repoPath, commit1, commit2) => electron_1.ipcRenderer.invoke('git:changed-files', repoPath, commit1, commit2),
    // Git Rebase & Blame
    gitRebase: (repoPath, targetBranch, options) => electron_1.ipcRenderer.invoke('git:rebase', repoPath, targetBranch, options),
    gitRebaseAbort: (repoPath) => electron_1.ipcRenderer.invoke('git:rebase-abort', repoPath),
    gitRebaseContinue: (repoPath) => electron_1.ipcRenderer.invoke('git:rebase-continue', repoPath),
    gitFileBlame: (repoPath, filePath) => electron_1.ipcRenderer.invoke('git:file-blame', repoPath, filePath),
    // Git Sync
    gitSyncConfigure: (config) => electron_1.ipcRenderer.invoke('git-sync:configure', config),
    gitSyncInit: () => electron_1.ipcRenderer.invoke('git-sync:init'),
    gitSyncPull: () => electron_1.ipcRenderer.invoke('git-sync:pull'),
    gitSyncPush: () => electron_1.ipcRenderer.invoke('git-sync:push'),
    gitSyncStatus: () => electron_1.ipcRenderer.invoke('git-sync:status'),
    onGitSyncStatusUpdated: (callback) => electron_1.ipcRenderer.on('git-sync:status-updated', (_e, data) => callback(data)),
};
//# sourceMappingURL=preload-git.js.map