import { type User, type Message, type FileTransfer, type ChatMessage } from './db-core';
declare function getAllUsers(): User[];
declare function upsertUser(user: User): User;
declare function updateUserOnlineStatus(userId: string, isOnline: boolean): string;
declare function deleteUser(userId: string): string;
declare function rowToMessage(row: any): Message;
declare function getAllMessages(): Message[];
declare function getMessagesWithUser(userId: string, currentUserId: string): Message[];
declare function addMessage(message: Message): Message;
declare function markMessageRead(messageId: string): string;
declare function getUnreadMessageCount(userId: string): number;
declare function rowToFileTransfer(row: any): FileTransfer;
declare function getAllFileTransfers(): FileTransfer[];
declare function addFileTransfer(transfer: FileTransfer): FileTransfer;
declare function updateFileTransferProgress(transferId: string, progress: number, status: string): string;
declare function completeFileTransfer(transferId: string, filePath: string): string;
declare function deleteFileTransfer(transferId: string): string;
declare function saveChatMessage(message: ChatMessage): ChatMessage;
declare function getChatMessages(limit?: number, offset?: number): any[];
declare function getChatMessagesBetween(userId1: string, userId2: string, limit?: number, offset?: number): any[];
declare function markMessagesAsRead(userId1: string, userId2: string): number;
declare function getUnreadCount(userId1: string, userId2: string): number;
declare function getAllUnreadCounts(myUserId: string): Record<string, number>;
declare const _default: {
    getAllUsers: typeof getAllUsers;
    upsertUser: typeof upsertUser;
    updateUserOnlineStatus: typeof updateUserOnlineStatus;
    deleteUser: typeof deleteUser;
    rowToMessage: typeof rowToMessage;
    getAllMessages: typeof getAllMessages;
    getMessagesWithUser: typeof getMessagesWithUser;
    addMessage: typeof addMessage;
    markMessageRead: typeof markMessageRead;
    getUnreadMessageCount: typeof getUnreadMessageCount;
    rowToFileTransfer: typeof rowToFileTransfer;
    getAllFileTransfers: typeof getAllFileTransfers;
    addFileTransfer: typeof addFileTransfer;
    updateFileTransferProgress: typeof updateFileTransferProgress;
    completeFileTransfer: typeof completeFileTransfer;
    deleteFileTransfer: typeof deleteFileTransfer;
    saveChatMessage: typeof saveChatMessage;
    getChatMessages: typeof getChatMessages;
    getChatMessagesBetween: typeof getChatMessagesBetween;
    markMessagesAsRead: typeof markMessagesAsRead;
    getUnreadCount: typeof getUnreadCount;
    getAllUnreadCounts: typeof getAllUnreadCounts;
};
export = _default;
