import { type Subtask, type Todo } from './db-core';
declare function rowToSubtask(row: any): Subtask;
declare function getSubtasksForTodo(todoId: string): Subtask[];
declare function addSubtask(subtask: Subtask): Subtask;
declare function updateSubtask(subtask: Subtask): Subtask;
declare function deleteSubtask(subtaskId: string): string;
declare function deleteSubtasksForTodo(todoId: string): string;
declare function updateTodoOrder(todos: Todo[]): boolean;
declare function calculateNextDate(currentDate: string, repeatType: string, repeatInterval: number): string;
declare function shouldCreateRepeatInstance(todo: Todo): boolean;
declare function createRepeatInstance(originalTodo: Todo): Todo | null;
declare function updateTodoCompletionBasedOnSubtasks(todoId: string): boolean;
declare const _default: {
    rowToSubtask: typeof rowToSubtask;
    getSubtasksForTodo: typeof getSubtasksForTodo;
    addSubtask: typeof addSubtask;
    updateSubtask: typeof updateSubtask;
    deleteSubtask: typeof deleteSubtask;
    deleteSubtasksForTodo: typeof deleteSubtasksForTodo;
    updateTodoOrder: typeof updateTodoOrder;
    calculateNextDate: typeof calculateNextDate;
    shouldCreateRepeatInstance: typeof shouldCreateRepeatInstance;
    createRepeatInstance: typeof createRepeatInstance;
    updateTodoCompletionBasedOnSubtasks: typeof updateTodoCompletionBasedOnSubtasks;
};
export = _default;
